# Generated by Django 4.2.1 on 2024-04-09 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='train',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='Train',
        ),
    ]
