# Generated by Django 4.2.1 on 2024-04-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trains', '0002_remove_schedule_destination_remove_schedule_train_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schedule', models.TimeField()),
                ('destination', models.CharField(max_length=100)),
            ],
        ),
    ]
